#! /bin/bash
# Used to satisfy some requirements by notes.yeshiwei.com

# Copyright (C) <2013>  <Hörmetjan Yiltiz, Shiwei Ye>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# html generation does not handle quirks, so NO QUIRKS!
echo "==================================================================="
echo "Please wait while correcting filenames"
echo "This will take a few minutes..."
echo ""
scary=(
' '
'）'
'（'
'\:'
'\?'
'\#'
'\%'
'\*'
'\]'
'\['
'\}'
'\{'
'\('
'\)'
'\)'
'_-_'
'-_'
'_-'
'_\._'
'\._'
'_\.'
'_____'
'____'
'___'
'__'
)

maxloop=$(echo ${#scary[@]})
number=1

for i in "${scary[@]}" ; do
  echo "$((${number}*100/${maxloop})) %: Now correcting ->${i}<-";
  number=$((${number}+1));

  # rename directories
  find . -type d -exec rename "s/${i}/_/g" '{}' \;

  # rename files
  find . -type f -exec rename "s/${i}/_/g" '{}' \;

  # rename mp3 files
  find . -type f -iname '*.mp3' -exec rename "s/${i}/_/g" '{}' \;
done
echo "==== No quirky filenames now! ====================================="

# Directory and other files has some special permissions
echo "==== Now Setting File and Folder's Permissions ====================";
find . -type d -exec chmod 755 '{}' \;
find . -type f -iname '*.mp3' -exec chmod 744 '{}' \;
