#! /bin/bash
# generate template using README.md

# Copyright (C) <2013>  <Hörmetjan Yiltiz>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# by hyiltiz <hyiltiz AT gmail DOT com> 
# Thu May  2 23:11:55 CST 2013

template=$2
line1=$(grep -n '</table>' $2 |awk -F ':' '{print $1}')
line2=$(grep -n '</body>' $2 |awk -F ':' '{print $1}')
echo $template
echo $line1
echo $line2
pwd

cp $2 .${2}
split $2 -l $line1 1
split $2 -l $(($line2-1)) 2

markdown $1 >> 1aa
cat 2ab >> 1aa
cp 1aa template.html
rm 1a* 2a*
